# Generated by Django 5.0.6 on 2024-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_datre_ordered_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_shipped',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=15000),
        ),
    ]
